/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipampa.view;

import br.unipampa.model.ItemConsignado;
import br.unipampa.model.ItemTombo;
import br.unipampa.model.LivroDaBiblioteca;
import br.unipampa.model.Usuario;
import br.unipampa.service.TipoDeRelatorio;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabrielbmoro
 */
public class FramePrincipal extends javax.swing.JFrame implements WindowListener {

    private DefaultTableModel modeloTabelaLivroCOnsignado;
    private DefaultTableModel modeloTabelaLivroTombo;
    private DefaultTableModel modeloTabelaBiblioteca;
    private Usuario usuario;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal(Usuario usuarioPorParametro) {
        initComponents();
        ConfiguracaoFrame.configFrameComTamanhoPersonalizado(this, 1000, 600);
        modeloTabelaLivroCOnsignado = (DefaultTableModel) jTableLivroConsignado.getModel();
        modeloTabelaLivroTombo = (DefaultTableModel) jTableLivroTombo.getModel();
        modeloTabelaBiblioteca = (DefaultTableModel) jTableBiblioteca.getModel();

        addWindowListener(this);
        this.usuario = usuarioPorParametro;
        if (this.usuario.isSouUsuarioAdministrador()) {
            jMenuUsuario.setEnabled(true);
        } else {
            jMenuUsuario.setEnabled(false);
        }
        revalidate();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAcervo = new javax.swing.JTabbedPane();
        panelLivroConsignado = new javax.swing.JPanel();
        panelButtonsLivroConsignado = new javax.swing.JPanel();
        btnNovoLivroConsignado = new javax.swing.JButton();
        btnListarLivroConsignado = new javax.swing.JButton();
        btnGerarRelatorioConsignado = new javax.swing.JButton();
        panelInternoLivroConsignado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivroConsignado = new javax.swing.JTable();
        btnSobreLivroConsignado = new javax.swing.JButton();
        btnDeletarLivroConsignado = new javax.swing.JButton();
        btnEditarLivroConsignado = new javax.swing.JButton();
        panelLivroTombo = new javax.swing.JPanel();
        panelButtonsLivroTombo = new javax.swing.JPanel();
        btnNovoLivroTombo = new javax.swing.JButton();
        btnListarLivroTombo = new javax.swing.JButton();
        btnGerarRelatorioTombo = new javax.swing.JButton();
        panelInternoLivroTombo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLivroTombo = new javax.swing.JTable();
        btnSobreLivroTombo = new javax.swing.JButton();
        btnEditarLivroTombo = new javax.swing.JButton();
        btnDeletarLivroTombo = new javax.swing.JButton();
        panelLivroBiblioteca = new javax.swing.JPanel();
        panelButtonsBiblioteca = new javax.swing.JPanel();
        btnNovoLivroBiblioteca = new javax.swing.JButton();
        btnListarLivroBiblioteca = new javax.swing.JButton();
        btnGerarRelatorioBiblioteca = new javax.swing.JButton();
        panelInternoBiblioteca = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBiblioteca = new javax.swing.JTable();
        btnEditarLivroBilioteca = new javax.swing.JButton();
        btnDeletarLivroBilioteca = new javax.swing.JButton();
        btnSobreLivroBilioteca = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemNovoUsuario = new javax.swing.JMenuItem();
        jMenuItemListarUsuario = new javax.swing.JMenuItem();
        jMenuItemAlterarSenhaDeAcesso = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuManual = new javax.swing.JMenuItem();
        jMenuSuporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnNovoLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/AddItem.png"))); // NOI18N
        btnNovoLivroConsignado.setToolTipText("Novo Item");
        btnNovoLivroConsignado.setMaximumSize(null);
        btnNovoLivroConsignado.setMinimumSize(null);
        btnNovoLivroConsignado.setPreferredSize(new java.awt.Dimension(44, 44));
        btnNovoLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLivroConsignadoActionPerformed(evt);
            }
        });

        btnListarLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/List.png"))); // NOI18N
        btnListarLivroConsignado.setToolTipText("LIstar Itens");
        btnListarLivroConsignado.setMaximumSize(null);
        btnListarLivroConsignado.setMinimumSize(null);
        btnListarLivroConsignado.setPreferredSize(new java.awt.Dimension(44, 44));
        btnListarLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivroConsignadoActionPerformed(evt);
            }
        });

        btnGerarRelatorioConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/PDF.png"))); // NOI18N
        btnGerarRelatorioConsignado.setToolTipText("Gerar Relatorio de Itens Cadastrados");
        btnGerarRelatorioConsignado.setMaximumSize(null);
        btnGerarRelatorioConsignado.setMinimumSize(null);
        btnGerarRelatorioConsignado.setPreferredSize(new java.awt.Dimension(44, 44));
        btnGerarRelatorioConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioConsignadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLivroConsignadoLayout = new javax.swing.GroupLayout(panelButtonsLivroConsignado);
        panelButtonsLivroConsignado.setLayout(panelButtonsLivroConsignadoLayout);
        panelButtonsLivroConsignadoLayout.setHorizontalGroup(
            panelButtonsLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLivroConsignadoLayout.createSequentialGroup()
                .addGroup(panelButtonsLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGerarRelatorioConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnNovoLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        panelButtonsLivroConsignadoLayout.setVerticalGroup(
            panelButtonsLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLivroConsignadoLayout.createSequentialGroup()
                .addComponent(btnNovoLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarRelatorioConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableLivroConsignado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Outro Código", "Tipo de Item", "Função", "Região"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLivroConsignado);

        btnSobreLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/View.png"))); // NOI18N
        btnSobreLivroConsignado.setToolTipText("Sobre o elemento");
        btnSobreLivroConsignado.setMaximumSize(null);
        btnSobreLivroConsignado.setMinimumSize(null);
        btnSobreLivroConsignado.setPreferredSize(new java.awt.Dimension(44, 44));
        btnSobreLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreLivroConsignadoActionPerformed(evt);
            }
        });

        btnDeletarLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/lixeira.png"))); // NOI18N
        btnDeletarLivroConsignado.setToolTipText("Remover Item");
        btnDeletarLivroConsignado.setMaximumSize(null);
        btnDeletarLivroConsignado.setMinimumSize(null);
        btnDeletarLivroConsignado.setPreferredSize(new java.awt.Dimension(44, 44));
        btnDeletarLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarLivroConsignadoActionPerformed(evt);
            }
        });

        btnEditarLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/editar.png"))); // NOI18N
        btnEditarLivroConsignado.setToolTipText("Editar Item");
        btnEditarLivroConsignado.setMaximumSize(null);
        btnEditarLivroConsignado.setMinimumSize(null);
        btnEditarLivroConsignado.setPreferredSize(new java.awt.Dimension(44, 44));
        btnEditarLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLivroConsignadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInternoLivroConsignadoLayout = new javax.swing.GroupLayout(panelInternoLivroConsignado);
        panelInternoLivroConsignado.setLayout(panelInternoLivroConsignadoLayout);
        panelInternoLivroConsignadoLayout.setHorizontalGroup(
            panelInternoLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLivroConsignadoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInternoLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnSobreLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletarLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelInternoLivroConsignadoLayout.setVerticalGroup(
            panelInternoLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLivroConsignadoLayout.createSequentialGroup()
                .addGroup(panelInternoLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(panelInternoLivroConsignadoLayout.createSequentialGroup()
                        .addComponent(btnSobreLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelLivroConsignadoLayout = new javax.swing.GroupLayout(panelLivroConsignado);
        panelLivroConsignado.setLayout(panelLivroConsignadoLayout);
        panelLivroConsignadoLayout.setHorizontalGroup(
            panelLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroConsignadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButtonsLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelInternoLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLivroConsignadoLayout.setVerticalGroup(
            panelLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroConsignadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInternoLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLivroConsignadoLayout.createSequentialGroup()
                        .addComponent(panelButtonsLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPaneAcervo.addTab("Livro Consignado", panelLivroConsignado);

        btnNovoLivroTombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/AddItem.png"))); // NOI18N
        btnNovoLivroTombo.setToolTipText("Novo Item");
        btnNovoLivroTombo.setMaximumSize(null);
        btnNovoLivroTombo.setMinimumSize(null);
        btnNovoLivroTombo.setPreferredSize(new java.awt.Dimension(44, 44));
        btnNovoLivroTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLivroTomboActionPerformed(evt);
            }
        });

        btnListarLivroTombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/List.png"))); // NOI18N
        btnListarLivroTombo.setToolTipText("LIstar Itens");
        btnListarLivroTombo.setMaximumSize(null);
        btnListarLivroTombo.setMinimumSize(null);
        btnListarLivroTombo.setPreferredSize(new java.awt.Dimension(44, 44));
        btnListarLivroTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivroTomboActionPerformed(evt);
            }
        });

        btnGerarRelatorioTombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/PDF.png"))); // NOI18N
        btnGerarRelatorioTombo.setToolTipText("Gerar Relatorio de Itens Cadastrados");
        btnGerarRelatorioTombo.setMaximumSize(null);
        btnGerarRelatorioTombo.setMinimumSize(null);
        btnGerarRelatorioTombo.setPreferredSize(new java.awt.Dimension(44, 44));
        btnGerarRelatorioTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioTomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLivroTomboLayout = new javax.swing.GroupLayout(panelButtonsLivroTombo);
        panelButtonsLivroTombo.setLayout(panelButtonsLivroTomboLayout);
        panelButtonsLivroTomboLayout.setHorizontalGroup(
            panelButtonsLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLivroTomboLayout.createSequentialGroup()
                .addGroup(panelButtonsLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListarLivroTombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnGerarRelatorioTombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovoLivroTombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        panelButtonsLivroTomboLayout.setVerticalGroup(
            panelButtonsLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLivroTomboLayout.createSequentialGroup()
                .addComponent(btnNovoLivroTombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarLivroTombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarRelatorioTombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableLivroTombo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Outro Código", "Tipo de Item", "Função", "Região"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableLivroTombo);

        btnSobreLivroTombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/View.png"))); // NOI18N
        btnSobreLivroTombo.setToolTipText("Sobre o elemento");
        btnSobreLivroTombo.setMaximumSize(null);
        btnSobreLivroTombo.setMinimumSize(null);
        btnSobreLivroTombo.setPreferredSize(new java.awt.Dimension(44, 44));
        btnSobreLivroTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreLivroTomboActionPerformed(evt);
            }
        });

        btnEditarLivroTombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/editar.png"))); // NOI18N
        btnEditarLivroTombo.setToolTipText("Editar Item");
        btnEditarLivroTombo.setMaximumSize(null);
        btnEditarLivroTombo.setMinimumSize(null);
        btnEditarLivroTombo.setPreferredSize(new java.awt.Dimension(44, 44));
        btnEditarLivroTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLivroTomboActionPerformed(evt);
            }
        });

        btnDeletarLivroTombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/lixeira.png"))); // NOI18N
        btnDeletarLivroTombo.setToolTipText("Remover Item");
        btnDeletarLivroTombo.setMaximumSize(null);
        btnDeletarLivroTombo.setMinimumSize(null);
        btnDeletarLivroTombo.setPreferredSize(new java.awt.Dimension(44, 44));
        btnDeletarLivroTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarLivroTomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInternoLivroTomboLayout = new javax.swing.GroupLayout(panelInternoLivroTombo);
        panelInternoLivroTombo.setLayout(panelInternoLivroTomboLayout);
        panelInternoLivroTomboLayout.setHorizontalGroup(
            panelInternoLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLivroTomboLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInternoLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEditarLivroTombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnDeletarLivroTombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSobreLivroTombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInternoLivroTomboLayout.setVerticalGroup(
            panelInternoLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLivroTomboLayout.createSequentialGroup()
                .addGroup(panelInternoLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(panelInternoLivroTomboLayout.createSequentialGroup()
                        .addComponent(btnSobreLivroTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarLivroTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarLivroTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelLivroTomboLayout = new javax.swing.GroupLayout(panelLivroTombo);
        panelLivroTombo.setLayout(panelLivroTomboLayout);
        panelLivroTomboLayout.setHorizontalGroup(
            panelLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroTomboLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButtonsLivroTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInternoLivroTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );
        panelLivroTomboLayout.setVerticalGroup(
            panelLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroTomboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInternoLivroTombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLivroTomboLayout.createSequentialGroup()
                        .addComponent(panelButtonsLivroTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPaneAcervo.addTab("Livro Tombo", panelLivroTombo);

        btnNovoLivroBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/AddItem.png"))); // NOI18N
        btnNovoLivroBiblioteca.setToolTipText("Novo Item");
        btnNovoLivroBiblioteca.setMaximumSize(null);
        btnNovoLivroBiblioteca.setMinimumSize(null);
        btnNovoLivroBiblioteca.setPreferredSize(new java.awt.Dimension(44, 44));
        btnNovoLivroBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLivroBibliotecaActionPerformed(evt);
            }
        });

        btnListarLivroBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/List.png"))); // NOI18N
        btnListarLivroBiblioteca.setToolTipText("LIstar Itens");
        btnListarLivroBiblioteca.setMaximumSize(null);
        btnListarLivroBiblioteca.setMinimumSize(null);
        btnListarLivroBiblioteca.setPreferredSize(new java.awt.Dimension(44, 44));
        btnListarLivroBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivroBibliotecaActionPerformed(evt);
            }
        });

        btnGerarRelatorioBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/PDF.png"))); // NOI18N
        btnGerarRelatorioBiblioteca.setToolTipText("Gerar Relatorio de Itens Cadastrados");
        btnGerarRelatorioBiblioteca.setMaximumSize(null);
        btnGerarRelatorioBiblioteca.setMinimumSize(null);
        btnGerarRelatorioBiblioteca.setPreferredSize(new java.awt.Dimension(44, 44));
        btnGerarRelatorioBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioBibliotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsBibliotecaLayout = new javax.swing.GroupLayout(panelButtonsBiblioteca);
        panelButtonsBiblioteca.setLayout(panelButtonsBibliotecaLayout);
        panelButtonsBibliotecaLayout.setHorizontalGroup(
            panelButtonsBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsBibliotecaLayout.createSequentialGroup()
                .addGroup(panelButtonsBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnListarLivroBiblioteca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnNovoLivroBiblioteca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGerarRelatorioBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        panelButtonsBibliotecaLayout.setVerticalGroup(
            panelButtonsBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsBibliotecaLayout.createSequentialGroup()
                .addComponent(btnNovoLivroBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarLivroBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarRelatorioBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableBiblioteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Outro Código", "Descrição", "Autor", "Ano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableBiblioteca);

        btnEditarLivroBilioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/editar.png"))); // NOI18N
        btnEditarLivroBilioteca.setToolTipText("Editar Item");
        btnEditarLivroBilioteca.setMaximumSize(null);
        btnEditarLivroBilioteca.setMinimumSize(null);
        btnEditarLivroBilioteca.setPreferredSize(new java.awt.Dimension(44, 44));
        btnEditarLivroBilioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLivroBiliotecaActionPerformed(evt);
            }
        });

        btnDeletarLivroBilioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/lixeira.png"))); // NOI18N
        btnDeletarLivroBilioteca.setToolTipText("Remover Item");
        btnDeletarLivroBilioteca.setMaximumSize(null);
        btnDeletarLivroBilioteca.setMinimumSize(null);
        btnDeletarLivroBilioteca.setPreferredSize(new java.awt.Dimension(44, 44));
        btnDeletarLivroBilioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarLivroBiliotecaActionPerformed(evt);
            }
        });

        btnSobreLivroBilioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/View.png"))); // NOI18N
        btnSobreLivroBilioteca.setToolTipText("Sobre o elemento");
        btnSobreLivroBilioteca.setMaximumSize(null);
        btnSobreLivroBilioteca.setMinimumSize(null);
        btnSobreLivroBilioteca.setPreferredSize(new java.awt.Dimension(44, 44));
        btnSobreLivroBilioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreLivroBiliotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInternoBibliotecaLayout = new javax.swing.GroupLayout(panelInternoBiblioteca);
        panelInternoBiblioteca.setLayout(panelInternoBibliotecaLayout);
        panelInternoBibliotecaLayout.setHorizontalGroup(
            panelInternoBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoBibliotecaLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInternoBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSobreLivroBilioteca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnEditarLivroBilioteca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletarLivroBilioteca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelInternoBibliotecaLayout.setVerticalGroup(
            panelInternoBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoBibliotecaLayout.createSequentialGroup()
                .addGroup(panelInternoBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(panelInternoBibliotecaLayout.createSequentialGroup()
                        .addComponent(btnSobreLivroBilioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarLivroBilioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarLivroBilioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelLivroBibliotecaLayout = new javax.swing.GroupLayout(panelLivroBiblioteca);
        panelLivroBiblioteca.setLayout(panelLivroBibliotecaLayout);
        panelLivroBibliotecaLayout.setHorizontalGroup(
            panelLivroBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButtonsBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInternoBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        panelLivroBibliotecaLayout.setVerticalGroup(
            panelLivroBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLivroBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInternoBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLivroBibliotecaLayout.createSequentialGroup()
                        .addComponent(panelButtonsBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPaneAcervo.addTab("Biblioteca", panelLivroBiblioteca);

        jMenu1.setText("Sistema");

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/usuarioPequeno.png"))); // NOI18N
        jMenuUsuario.setText("Usuários");

        jMenuItemNovoUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/addPequeno.png"))); // NOI18N
        jMenuItemNovoUsuario.setText("Adicionar Novo Usuário");
        jMenuItemNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemNovoUsuario);

        jMenuItemListarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemListarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/listarPequeno.png"))); // NOI18N
        jMenuItemListarUsuario.setText("Listar Usuários");
        jMenuItemListarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemListarUsuario);

        jMenu1.add(jMenuUsuario);

        jMenuItemAlterarSenhaDeAcesso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAlterarSenhaDeAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/alterarSenha.png"))); // NOI18N
        jMenuItemAlterarSenhaDeAcesso.setText("Alterar Senha de Acesso");
        jMenuItemAlterarSenhaDeAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarSenhaDeAcessoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAlterarSenhaDeAcesso);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/desligar.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/manual.png"))); // NOI18N
        jMenuManual.setText("Manual");
        jMenuManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManualActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuManual);

        jMenuSuporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuSuporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/suporte.png"))); // NOI18N
        jMenuSuporte.setText("Suporte");
        jMenuSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuporteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSuporte);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPaneAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 910, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneAcervo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivroConsignadoActionPerformed
        listarTabelaLivroConsignado(true);
    }//GEN-LAST:event_btnListarLivroConsignadoActionPerformed

    private void listarTabelaLivroConsignado(boolean mensagem) {
        /*Limpar Tabela*/
        if (modeloTabelaLivroCOnsignado != null) {
            modeloTabelaLivroCOnsignado.setNumRows(0);
            ItemConsignado itemConsignado = new ItemConsignado();
            List listaDeREgistros = itemConsignado.recuperarTodos();
            if (listaDeREgistros != null && !listaDeREgistros.isEmpty()) {
                for (Object objetoTemp : listaDeREgistros) {
                    ItemConsignado itemConsignadoTemporario = (ItemConsignado) objetoTemp;
                    modeloTabelaLivroCOnsignado.addRow(new Object[]{
                        itemConsignadoTemporario.getID(),
                        itemConsignadoTemporario.getOutroCodigo(),
                        itemConsignadoTemporario.getTipoObjeto(),
                        itemConsignadoTemporario.getFuncaoEspecifica(),
                        itemConsignadoTemporario.getRegiao()
                    });
                }
            } else if (mensagem == true) {
                GeradorDeMensagem.exibirMensagemDeInformacao("Nenhum registro encontrado!", "Alerta ao Usuário");
            }
        }
    }

    private void listarTabelaLivroTombo(boolean mensagem) {
        /*Limpar Tabela*/
        if (modeloTabelaLivroTombo != null) {
            modeloTabelaLivroTombo.setNumRows(0);
            ItemTombo itemTombo = new ItemTombo();
            List listaDeREgistros = itemTombo.recuperarTodos();
            if (listaDeREgistros != null && !listaDeREgistros.isEmpty()) {
                for (Object objetoTemp : listaDeREgistros) {
                    ItemTombo itemTomboTemp = (ItemTombo) objetoTemp;
                    modeloTabelaLivroTombo.addRow(new Object[]{
                        itemTomboTemp.getID(),
                        itemTomboTemp.getOutroCodigo(),
                        itemTomboTemp.getTipoObjeto(),
                        itemTomboTemp.getFuncaoEspecifica(),
                        itemTomboTemp.getRegiao()
                    });
                }
            } else if (mensagem == true) {
                GeradorDeMensagem.exibirMensagemDeInformacao("Nenhum registro encontrado!", "Alerta ao Usuário");
            }
        }
    }

    private void listarTabelaBiblioteca(boolean mensagem) {
        /*Limpar Tabela*/
        if (modeloTabelaBiblioteca != null) {
            modeloTabelaBiblioteca.setNumRows(0);
            LivroDaBiblioteca livroDaBiblioteca = new LivroDaBiblioteca();
            List listaDeREgistros = livroDaBiblioteca.recuperarTodos();
            if (listaDeREgistros != null && !listaDeREgistros.isEmpty()) {
                for (Object objetoTemp : listaDeREgistros) {
                    LivroDaBiblioteca livroDaBibliotecaTemp = (LivroDaBiblioteca) objetoTemp;
                    modeloTabelaBiblioteca.addRow(new Object[]{
                        livroDaBibliotecaTemp.getID(),
                        livroDaBibliotecaTemp.getOutroCodigo(),
                        livroDaBibliotecaTemp.getNomeLivro(),
                        livroDaBibliotecaTemp.getNomeAutor(),
                        livroDaBibliotecaTemp.getAnoLacamento()
                    });
                }
            } else if (mensagem == true) {
                GeradorDeMensagem.exibirMensagemDeInformacao("Nenhum registro encontrado!", "Alerta ao Usuário");
            }
        }
    }
    private void btnDeletarLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarLivroConsignadoActionPerformed
        try {
            int linhaSelecionada = jTableLivroConsignado.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroCOnsignado.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {
                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemConsignado itemConsignado = new ItemConsignado();
                    Object objetoASerExcluido = itemConsignado.recuperarPeloID(idLong);
                    if (objetoASerExcluido != null) {
                        if (GeradorDeMensagem.exibirMensagemDeConfirmacao("Deseja remover o registro?", "Alerta ao Usuário") == true) {
                            boolean resultado = itemConsignado.deletar(objetoASerExcluido);
                            if (resultado) {
                                GeradorDeMensagem.exibirMensagemDeInformacao("Registro Excluído com sucesso!", "Alerta ao Usuário");
                                listarTabelaLivroConsignado(false);
                            } else {
                                GeradorDeMensagem.exibirMensagemDeErro("Ocorreu um problema, realize a operação mais tarde!");
                            }
                        }
                    } else {
                        GeradorDeMensagem.exibirMensagemDeErro("Ocorreu um problema, realize a operação mais tarde!");
                    }
                }
            }

        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnDeletarLivroConsignadoActionPerformed

    private void btnSobreLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreLivroConsignadoActionPerformed
        try {
            int linhaSelecionada = jTableLivroConsignado.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroCOnsignado.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {

                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemConsignado itemConsignado = new ItemConsignado();
                    ItemConsignado itemConsignadoTemporario = (ItemConsignado) itemConsignado.recuperarPeloID(idLong);
                    if (itemConsignadoTemporario != null) {
                        new FrameInfoEditLivroConsignado(itemConsignadoTemporario, true);
                    }
                }

            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
            }
        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnSobreLivroConsignadoActionPerformed

    private void btnEditarLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLivroConsignadoActionPerformed
        try {
            int linhaSelecionada = jTableLivroConsignado.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroCOnsignado.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {

                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemConsignado itemConsignado = new ItemConsignado();
                    ItemConsignado itemConsignadoTemporario = (ItemConsignado) itemConsignado.recuperarPeloID(idLong);
                    if (itemConsignadoTemporario != null) {
                        new FrameInfoEditLivroConsignado(itemConsignadoTemporario,
                                false);
                    }
                }

            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
            }
        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnEditarLivroConsignadoActionPerformed

    private void btnNovoLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLivroConsignadoActionPerformed
        new FrameNovoLivroConsignado();
    }//GEN-LAST:event_btnNovoLivroConsignadoActionPerformed

    private void btnGerarRelatorioConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioConsignadoActionPerformed
        new FrameDeGeracaoDeRelatorios(TipoDeRelatorio.ITEM_CONSIGNADO);
    }//GEN-LAST:event_btnGerarRelatorioConsignadoActionPerformed

    private void btnNovoLivroTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLivroTomboActionPerformed
        new FrameNovoItemTombo();
    }//GEN-LAST:event_btnNovoLivroTomboActionPerformed

    private void btnListarLivroTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivroTomboActionPerformed
        listarTabelaLivroTombo(true);
    }//GEN-LAST:event_btnListarLivroTomboActionPerformed

    private void btnGerarRelatorioTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioTomboActionPerformed
        new FrameDeGeracaoDeRelatorios(TipoDeRelatorio.ITEM_TOMBO);
    }//GEN-LAST:event_btnGerarRelatorioTomboActionPerformed

    private void btnEditarLivroTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLivroTomboActionPerformed
        try {
            int linhaSelecionada = jTableLivroTombo.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroTombo.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {

                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemTombo itemTombo = new ItemTombo();
                    ItemTombo itemTomboTemporario = (ItemTombo) itemTombo.recuperarPeloID(idLong);
                    if (itemTomboTemporario != null) {
                        new FrameInfoEditLivroCombo(itemTomboTemporario,
                                false);
                    }
                }

            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
            }
        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnEditarLivroTomboActionPerformed

    private void btnDeletarLivroTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarLivroTomboActionPerformed
        try {
            int linhaSelecionada = jTableLivroTombo.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroTombo.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {
                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemTombo itemTombo = new ItemTombo();
                    Object objetoASerExcluido = itemTombo.recuperarPeloID(idLong);
                    if (objetoASerExcluido != null) {
                        if (GeradorDeMensagem.exibirMensagemDeConfirmacao("Deseja remover o registro?", "Alerta ao Usuário") == true) {
                            boolean resultado = itemTombo.deletar(objetoASerExcluido);
                            if (resultado) {
                                GeradorDeMensagem.exibirMensagemDeInformacao("Registro Excluído com sucesso!", "Alerta ao Usuário");
                                listarTabelaLivroTombo(false);
                            } else {
                                GeradorDeMensagem.exibirMensagemDeErro("Ocorreu um problema, realize a operação mais tarde!");
                            }
                        }
                    } else {
                        GeradorDeMensagem.exibirMensagemDeErro("Ocorreu um problema, realize a operação mais tarde!");
                    }
                }
            }

        } catch (Exception erro) {
            erro.printStackTrace();
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnDeletarLivroTomboActionPerformed

    private void btnSobreLivroTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreLivroTomboActionPerformed
        try {
            int linhaSelecionada = jTableLivroTombo.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroTombo.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {

                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemTombo itemTombo = new ItemTombo();
                    ItemTombo itemTomboTemporario = (ItemTombo) itemTombo.recuperarPeloID(idLong);
                    if (itemTomboTemporario != null) {
                        new FrameInfoEditLivroCombo(itemTomboTemporario, true);
                    }
                }

            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
            }
        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnSobreLivroTomboActionPerformed

    private void btnNovoLivroBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLivroBibliotecaActionPerformed
        new FrameNovoLivroBiblioteca();
    }//GEN-LAST:event_btnNovoLivroBibliotecaActionPerformed

    private void btnListarLivroBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivroBibliotecaActionPerformed
        listarTabelaBiblioteca(true);
    }//GEN-LAST:event_btnListarLivroBibliotecaActionPerformed

    private void btnGerarRelatorioBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioBibliotecaActionPerformed
        new FrameDeGeracaoDeRelatorios(TipoDeRelatorio.ITEM_BIBLIOTECA);
    }//GEN-LAST:event_btnGerarRelatorioBibliotecaActionPerformed

    private void btnEditarLivroBiliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLivroBiliotecaActionPerformed
        try {
            int linhaSelecionada = jTableBiblioteca.getSelectedRow();
            Object idDeElemento = modeloTabelaBiblioteca.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {

                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    LivroDaBiblioteca livroDaBiblioteca = new LivroDaBiblioteca();
                    LivroDaBiblioteca livroDaBibliotecaTemporario = (LivroDaBiblioteca) livroDaBiblioteca.recuperarPeloID(idLong);
                    if (livroDaBibliotecaTemporario != null) {
                        new FrameInfoEditLivroBiblioteca(livroDaBibliotecaTemporario,
                                false);
                    }
                }

            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
            }
        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnEditarLivroBiliotecaActionPerformed

    private void btnDeletarLivroBiliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarLivroBiliotecaActionPerformed
        try {
            int linhaSelecionada = jTableBiblioteca.getSelectedRow();
            Object idDeElemento = modeloTabelaBiblioteca.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {
                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    LivroDaBiblioteca livroDaBiblioteca = new LivroDaBiblioteca();
                    Object objetoASerExcluido = livroDaBiblioteca.recuperarPeloID(idLong);
                    if (objetoASerExcluido != null) {
                        if (GeradorDeMensagem.exibirMensagemDeConfirmacao("Deseja remover o registro?", "Alerta ao Usuário") == true) {
                            boolean resultado = livroDaBiblioteca.deletar(objetoASerExcluido);
                            if (resultado) {
                                GeradorDeMensagem.exibirMensagemDeInformacao("Registro Excluído com sucesso!", "Alerta ao Usuário");
                                listarTabelaBiblioteca(false);
                            } else {
                                GeradorDeMensagem.exibirMensagemDeErro("Ocorreu um problema, realize a operação mais tarde!");
                            }
                        }
                    } else {
                        GeradorDeMensagem.exibirMensagemDeErro("Ocorreu um problema, realize a operação mais tarde!");
                    }
                }
            }

        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnDeletarLivroBiliotecaActionPerformed

    private void btnSobreLivroBiliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreLivroBiliotecaActionPerformed
        try {
            int linhaSelecionada = jTableBiblioteca.getSelectedRow();
            Object idDeElemento = modeloTabelaBiblioteca.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {

                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    LivroDaBiblioteca livroDaBiblioteca = new LivroDaBiblioteca();
                    LivroDaBiblioteca livroDaBibliotecaTemporario = (LivroDaBiblioteca) livroDaBiblioteca.recuperarPeloID(idLong);
                    if (livroDaBibliotecaTemporario != null) {
                        new FrameInfoEditLivroBiblioteca(livroDaBibliotecaTemporario, true);
                    }
                }

            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
            }
        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operação!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnSobreLivroBiliotecaActionPerformed

    private void jMenuItemNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoUsuarioActionPerformed
        new FrameCadastroUsuario();
    }//GEN-LAST:event_jMenuItemNovoUsuarioActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        if (GeradorDeMensagem.exibirMensagemDeConfirmacao("Você deseja realmente sair da aplicação?", "Alerta ao Usuário") == true) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarUsuarioActionPerformed
        new FrameListarUsuario();
    }//GEN-LAST:event_jMenuItemListarUsuarioActionPerformed

    private void jMenuItemAlterarSenhaDeAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarSenhaDeAcessoActionPerformed
        if (this.usuario != null) {
            new FrameAlterarSenha(this.usuario);
        }
    }//GEN-LAST:event_jMenuItemAlterarSenhaDeAcessoActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jMenuManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManualActionPerformed
        GeradorDeMensagem.exibirMensagemDeErro("O manual será adicionado em breve!");
    }//GEN-LAST:event_jMenuManualActionPerformed

    private void jMenuSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuporteActionPerformed
        GeradorDeMensagem.exibirMensagemDeErro("O suporte será adicionado em breve!");
    }//GEN-LAST:event_jMenuSuporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarLivroBilioteca;
    private javax.swing.JButton btnDeletarLivroConsignado;
    private javax.swing.JButton btnDeletarLivroTombo;
    private javax.swing.JButton btnEditarLivroBilioteca;
    private javax.swing.JButton btnEditarLivroConsignado;
    private javax.swing.JButton btnEditarLivroTombo;
    private javax.swing.JButton btnGerarRelatorioBiblioteca;
    private javax.swing.JButton btnGerarRelatorioConsignado;
    private javax.swing.JButton btnGerarRelatorioTombo;
    private javax.swing.JButton btnListarLivroBiblioteca;
    private javax.swing.JButton btnListarLivroConsignado;
    private javax.swing.JButton btnListarLivroTombo;
    private javax.swing.JButton btnNovoLivroBiblioteca;
    private javax.swing.JButton btnNovoLivroConsignado;
    private javax.swing.JButton btnNovoLivroTombo;
    private javax.swing.JButton btnSobreLivroBilioteca;
    private javax.swing.JButton btnSobreLivroConsignado;
    private javax.swing.JButton btnSobreLivroTombo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlterarSenhaDeAcesso;
    private javax.swing.JMenuItem jMenuItemListarUsuario;
    private javax.swing.JMenuItem jMenuItemNovoUsuario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuManual;
    private javax.swing.JMenuItem jMenuSuporte;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneAcervo;
    private javax.swing.JTable jTableBiblioteca;
    private javax.swing.JTable jTableLivroConsignado;
    private javax.swing.JTable jTableLivroTombo;
    private javax.swing.JPanel panelButtonsBiblioteca;
    private javax.swing.JPanel panelButtonsLivroConsignado;
    private javax.swing.JPanel panelButtonsLivroTombo;
    private javax.swing.JPanel panelInternoBiblioteca;
    private javax.swing.JPanel panelInternoLivroConsignado;
    private javax.swing.JPanel panelInternoLivroTombo;
    private javax.swing.JPanel panelLivroBiblioteca;
    private javax.swing.JPanel panelLivroConsignado;
    private javax.swing.JPanel panelLivroTombo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
        if (GeradorDeMensagem.exibirMensagemDeConfirmacao("Você deseja realmente sair da aplicação?", "Alerta ao Usuário") == true) {
            System.exit(0);
        }
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
        listarTabelaLivroConsignado(false);
        listarTabelaLivroTombo(false);
        listarTabelaBiblioteca(false);
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
