/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipampa.view;

import br.unipampa.model.Usuario;
import br.unipampa.service.CriptografiaMD5;

/**
 *
 * @author gabrielbmoro
 */
public class FrameAlterarSenha extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form FrameAlterarSenha
     */
    public FrameAlterarSenha(Usuario usuarioParametro) {
        initComponents();
        this.usuario = usuarioParametro;
        ConfiguracaoFrame.configFrameComTamanhoPersonalizado(this, 392, 182);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JPasswordField();
        btnAlterarSenha = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSenhaAntiga = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar Senha");

        jLabel1.setText("Nova Senha:");

        btnAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/cadastrar.png"))); // NOI18N
        btnAlterarSenha.setText("Atualizar Senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha Antiga:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(txtNovaSenha)
                    .addComponent(btnAlterarSenha)
                    .addComponent(jLabel2)
                    .addComponent(txtSenhaAntiga, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterarSenha)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        String senhaAntiga = CriptografiaMD5.codificar(this.txtSenhaAntiga.getText());
        String senhaNova = this.txtNovaSenha.getText();

        if (senhaAntiga.equalsIgnoreCase(this.usuario.getSenha())) {
            this.usuario.setSenha(CriptografiaMD5.codificar(senhaNova));
            if (this.usuario.alterar(this.usuario)) {
                GeradorDeMensagem.exibirMensagemDeInformacao("Senha alterada com sucesso!", "Alerta ao Usuário");
            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Ocorreu um problema, realize a operação novamente!", "Alerta ao Usuário");
            }
        } else {
            GeradorDeMensagem.exibirMensagemDeInformacao("Digite sua senha novamente, a mesma não confere!", "Alerta ao Usuário");
        }
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtNovaSenha;
    private javax.swing.JPasswordField txtSenhaAntiga;
    // End of variables declaration//GEN-END:variables
}
