/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unipampa.view;

import br.unipampa.model.ItemConsignado;
import br.unipampa.service.GerarRelatorioEmPdf;
import br.unipampa.service.TipoDeRelatorio;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabrielbmoro
 */
public class FramePrincipal extends javax.swing.JFrame implements WindowListener{

    private DefaultTableModel modeloTabelaLivroCOnsignado;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        ConfiguracaoFrame.configFrameComTamanhoPersonalizado(this, 1000, 600);
        modeloTabelaLivroCOnsignado = (DefaultTableModel) jTableLivroConsignado.getModel();
        addWindowListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAcervo = new javax.swing.JTabbedPane();
        panelLivroConsignado = new javax.swing.JPanel();
        panelButtonsLivroConsignado = new javax.swing.JPanel();
        btnNovoLivroConsignado = new javax.swing.JButton();
        btnListarLivroConsignado = new javax.swing.JButton();
        btnGerarRelatorio = new javax.swing.JButton();
        panelInternoLivroConsignado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivroConsignado = new javax.swing.JTable();
        btnEditarLivroConsignado = new javax.swing.JButton();
        btnDeletarLivroConsignado = new javax.swing.JButton();
        btnSobreLivroConsignado = new javax.swing.JButton();
        panelLivroTombo = new javax.swing.JPanel();
        panelLivroBiblioteca = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNovoLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/add.png"))); // NOI18N
        btnNovoLivroConsignado.setToolTipText("Novo Item");
        btnNovoLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLivroConsignadoActionPerformed(evt);
            }
        });

        btnListarLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/listar.png"))); // NOI18N
        btnListarLivroConsignado.setToolTipText("LIstar Itens");
        btnListarLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivroConsignadoActionPerformed(evt);
            }
        });

        btnGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/exportar.png"))); // NOI18N
        btnGerarRelatorio.setToolTipText("Gerar Relatorio de Itens Cadastrados");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLivroConsignadoLayout = new javax.swing.GroupLayout(panelButtonsLivroConsignado);
        panelButtonsLivroConsignado.setLayout(panelButtonsLivroConsignadoLayout);
        panelButtonsLivroConsignadoLayout.setHorizontalGroup(
            panelButtonsLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLivroConsignadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonsLivroConsignadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovoLivroConsignado))
                    .addGroup(panelButtonsLivroConsignadoLayout.createSequentialGroup()
                        .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelButtonsLivroConsignadoLayout.setVerticalGroup(
            panelButtonsLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLivroConsignadoLayout.createSequentialGroup()
                .addComponent(btnNovoLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarLivroConsignado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerarRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableLivroConsignado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Outro Codigo", "Tipo de Item", "Funçao", "Regiao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLivroConsignado);

        btnEditarLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/editar.png"))); // NOI18N
        btnEditarLivroConsignado.setToolTipText("Editar Item");
        btnEditarLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLivroConsignadoActionPerformed(evt);
            }
        });

        btnDeletarLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/lixeira.png"))); // NOI18N
        btnDeletarLivroConsignado.setToolTipText("Remover Item");
        btnDeletarLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarLivroConsignadoActionPerformed(evt);
            }
        });

        btnSobreLivroConsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unipampa/view/icons/escolhas.png"))); // NOI18N
        btnSobreLivroConsignado.setToolTipText("Sobre o elemento");
        btnSobreLivroConsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreLivroConsignadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInternoLivroConsignadoLayout = new javax.swing.GroupLayout(panelInternoLivroConsignado);
        panelInternoLivroConsignado.setLayout(panelInternoLivroConsignadoLayout);
        panelInternoLivroConsignadoLayout.setHorizontalGroup(
            panelInternoLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLivroConsignadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelInternoLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeletarLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSobreLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarLivroConsignado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInternoLivroConsignadoLayout.setVerticalGroup(
            panelInternoLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLivroConsignadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnSobreLivroConsignado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarLivroConsignado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletarLivroConsignado)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(panelInternoLivroConsignadoLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelLivroConsignadoLayout = new javax.swing.GroupLayout(panelLivroConsignado);
        panelLivroConsignado.setLayout(panelLivroConsignadoLayout);
        panelLivroConsignadoLayout.setHorizontalGroup(
            panelLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroConsignadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButtonsLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelInternoLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        panelLivroConsignadoLayout.setVerticalGroup(
            panelLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroConsignadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLivroConsignadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInternoLivroConsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLivroConsignadoLayout.createSequentialGroup()
                        .addComponent(panelButtonsLivroConsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPaneAcervo.addTab("Livro Consignado", panelLivroConsignado);

        javax.swing.GroupLayout panelLivroTomboLayout = new javax.swing.GroupLayout(panelLivroTombo);
        panelLivroTombo.setLayout(panelLivroTomboLayout);
        panelLivroTomboLayout.setHorizontalGroup(
            panelLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        panelLivroTomboLayout.setVerticalGroup(
            panelLivroTomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jTabbedPaneAcervo.addTab("Livro Tombo", panelLivroTombo);

        javax.swing.GroupLayout panelLivroBibliotecaLayout = new javax.swing.GroupLayout(panelLivroBiblioteca);
        panelLivroBiblioteca.setLayout(panelLivroBibliotecaLayout);
        panelLivroBibliotecaLayout.setHorizontalGroup(
            panelLivroBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        panelLivroBibliotecaLayout.setVerticalGroup(
            panelLivroBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jTabbedPaneAcervo.addTab("Biblioteca", panelLivroBiblioteca);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneAcervo)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneAcervo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivroConsignadoActionPerformed
        listarTabelaLivroConsignado();
    }//GEN-LAST:event_btnListarLivroConsignadoActionPerformed

    private void listarTabelaLivroConsignado() {
        /*Limpar Tabela*/
        modeloTabelaLivroCOnsignado.setNumRows(0);
        ItemConsignado itemConsignado = new ItemConsignado();
        List listaDeREgistros = itemConsignado.recuperarTodos();
        if (listaDeREgistros != null && !listaDeREgistros.isEmpty()) {
            for (Object objetoTemp : listaDeREgistros) {
                ItemConsignado itemConsignadoTemporario = (ItemConsignado) objetoTemp;
                modeloTabelaLivroCOnsignado.addRow(new Object[]{
                    itemConsignadoTemporario.getID(),
                    itemConsignadoTemporario.getOutroCodigo(),
                    itemConsignadoTemporario.getTipoObjeto(),
                    itemConsignadoTemporario.getFuncaoEspecifica(),
                    itemConsignadoTemporario.getRegiao()
                });
            }
        }
    }
    private void btnDeletarLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarLivroConsignadoActionPerformed
        try {
            int linhaSelecionada = jTableLivroConsignado.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroCOnsignado.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {
                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemConsignado itemConsignado = new ItemConsignado();
                    Object objetoASerExcluido = itemConsignado.recuperarPeloID(idLong);
                    if (objetoASerExcluido != null) {
                        boolean resultado = itemConsignado.deletar(objetoASerExcluido);
                        if (resultado) {
                            GeradorDeMensagem.exibirMensagemDeInformacao("Registro Excluido com sucesso!", "Alerta ao Usuario");
                            listarTabelaLivroConsignado();
                        } else {
                            GeradorDeMensagem.exibirMensagemDeErro("Ocorreu um problema, realize a operaçao mais tarde!");
                        }
                    } else {
                        GeradorDeMensagem.exibirMensagemDeErro("Ocorreu um problema, realize a operaçao mais tarde!");
                    }
                }
            }

        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operaçao!", "Alerta de Usuario");
        }
    }//GEN-LAST:event_btnDeletarLivroConsignadoActionPerformed

    private void btnSobreLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreLivroConsignadoActionPerformed
        try {
            int linhaSelecionada = jTableLivroConsignado.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroCOnsignado.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {

                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemConsignado itemConsignado = new ItemConsignado();
                    ItemConsignado itemConsignadoTemporario = (ItemConsignado) itemConsignado.recuperarPeloID(idLong);
                    if (itemConsignadoTemporario != null) {
                        new FrameInfoEditLivroConsignado(itemConsignadoTemporario, true);
                    }
                }

            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operaçao!", "Alerta de Usuario");
            }
        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operaçao!", "Alerta de Usuario");
        }
    }//GEN-LAST:event_btnSobreLivroConsignadoActionPerformed

    private void btnEditarLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLivroConsignadoActionPerformed
        try {
            int linhaSelecionada = jTableLivroConsignado.getSelectedRow();
            Object idDeElemento = modeloTabelaLivroCOnsignado.getValueAt(linhaSelecionada, 0);
            if (idDeElemento != null) {

                Long idLong = Long.parseLong(idDeElemento.toString());
                if (idLong != 0) {
                    ItemConsignado itemConsignado = new ItemConsignado();
                    ItemConsignado itemConsignadoTemporario = (ItemConsignado) itemConsignado.recuperarPeloID(idLong);
                    if (itemConsignadoTemporario != null) {
                         new FrameInfoEditLivroConsignado(itemConsignadoTemporario,
                                false);
                    }
                }

            } else {
                GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operaçao!", "Alerta de Usuario");
            }
        } catch (Exception erro) {
            GeradorDeMensagem.exibirMensagemDeInformacao("Selecione uma linha para realizar a operaçao!", "Alerta de Usuario");
        }
    }//GEN-LAST:event_btnEditarLivroConsignadoActionPerformed

    private void btnNovoLivroConsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLivroConsignadoActionPerformed
        new FrameNovoLivroConsignado();
    }//GEN-LAST:event_btnNovoLivroConsignadoActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
     new FrameDeGeracaoDeRelatorios(TipoDeRelatorio.ITEM_CONSIGNADO);
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarLivroConsignado;
    private javax.swing.JButton btnEditarLivroConsignado;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnListarLivroConsignado;
    private javax.swing.JButton btnNovoLivroConsignado;
    private javax.swing.JButton btnSobreLivroConsignado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneAcervo;
    private javax.swing.JTable jTableLivroConsignado;
    private javax.swing.JPanel panelButtonsLivroConsignado;
    private javax.swing.JPanel panelInternoLivroConsignado;
    private javax.swing.JPanel panelLivroBiblioteca;
    private javax.swing.JPanel panelLivroConsignado;
    private javax.swing.JPanel panelLivroTombo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
 if(GeradorDeMensagem.exibirMensagemDeConfirmacao("Voce deseja realmente sair da aplicaçao?", "Alerta de Usuario")){
           System.exit(0);
       }
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
